### PR TITLE
fixed #21 sintax error, support any php 5+ or 7+

### LINKED ISSUE #21: bug: Parse error: syntax error, unexpected '.', expecting '&'
i got and error when try to install this attachment preview:

it said:  Successfully installed a plugin but get and error: 

```
Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/share/www-data/osticket/include/plugins/attachment_preview/class.AttachmentPreviewPlugin.php on line 647
```

### PR DESCRIPTION
**Pull request by mckaygerhard**
the pluguin works perfect with osticket 1.9 but osticket 1.9 works with php 5.3 so able to work with any version.

i'll explain, if log parsing hav more that one arg, so the debug will parse and try to extract the rest of the arguments.. so no problem if are manage as array.. 

that's the reason why the secon arg its init with null to able to use with two or more on one arg only

### CODE REVIEW

File: class.AttachmentPreviewPlugin.php [hunk 1]
```diff
@@ -657,12 +657,12 @@ private function debug_log(...$args) {
...
      * @param mixed $args
      */
-    private function log($text, ...$args) {
+    private function log($text, $args=null) {
         // Log to system, if available
         global $ost;
 
-        if (func_num_args() > 1) {
-            $text = vsprintf($text, ...$args);
+        if (is_array($args) AND count($args > 1)) {
```
Comment (mckaygerhard) [inline class.AttachmentPreviewPlugin.php]: urrgg an error.. must be "count($args) > 1"

**Comment by clonemeagain** [comment]
I mentioned this in #21, simply removing the splat operator will introduce an error unless the args are accounted for.

**Comment by mckaygerhard** [comment]
let me made the modifications, but in the future if you wish , you can directly alter the pull commit too..

i answered about the "unsupported" misc.meaning word and tests in the issue comment.. great work
